# Generated by Django 2.2.5 on 2019-09-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=49, null=True, verbose_name='Bank Name')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
            },
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.CharField(max_length=11, verbose_name='IFSC')),
                ('bank_id', models.IntegerField(blank=True, null=True, verbose_name='Bank ID')),
                ('branch', models.CharField(blank=True, max_length=74, null=True, verbose_name='Branch')),
                ('address', models.CharField(blank=True, max_length=195, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('district', models.CharField(blank=True, max_length=50, null=True, verbose_name='District')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('bank_name', models.CharField(blank=True, max_length=49, null=True, verbose_name='Bank Name')),
            ],
            options={
                'verbose_name': 'Bank Branch',
                'verbose_name_plural': 'Bank Branches',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.CharField(max_length=11, verbose_name='IFSC')),
                ('bank_id', models.IntegerField(blank=True, null=True, verbose_name='Bank ID')),
                ('branch', models.CharField(blank=True, max_length=74, null=True, verbose_name='Branch')),
                ('address', models.CharField(blank=True, max_length=195, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('district', models.CharField(blank=True, max_length=50, null=True, verbose_name='District')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
    ]
